version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
#      - REDIS_PASSWORD=password
      - REDIS_PORT=6379

volumes:
  redis-data: {}